apt:
  debconf_selections: 
    set1: "debconf debconf/frontend select Noninteractive"
packages:
    - pwgen
    - zsh
    - curl
    - git
    - sudo
    - locales
    - vim
    - wget
    - iputils-ping
    - iproute2
    - jq 
    - unzip 
    - python3 
    - apt-transport-https 
    - ca-certificates 
    - software-properties-common 
    - jid
package_update: true
package_upgrade: true
package_reboot_if_required: true
locale: en_US.UTF-8
write_files:
  - content: |
      export ZSH="$HOME/.oh-my-zsh"
      export LC_ALL=en_US.UTF-8
      export LANG=en_US.UTF-8

      ZSH_THEME="agnoster"

      plugins=(git)

      source $ZSH/oh-my-zsh.sh

      zstyle ':urlglobber' url-other-schema

      autoload run-help

      prompt_end() {
        if [[ -n $CURRENT_BG ]]; then
            print -n "%{%k%F{$CURRENT_BG}%}$SEGMENT_SEPARATOR"
        else
            print -n "%{%k%}"
        fi

        print -n "%{%f%}"
        CURRENT_BG=''

        #Adds the new line and ➜ as the start character.
        printf "\n ➜";
      }
    owner: ubuntu:ubuntu
    path: /home/ubuntu/.zshrc
  - content: |
      set expandtab
      set shiftwidth=2
      set softtabstop=2
      filetype plugin indent on
    owner: ubuntu:ubuntu
    path: /home/ubuntu/.vimrc
runcmd:
  - chown -R ubuntu:ubuntu /home/ubuntu
  - su -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" ubuntu
  - su -c "sed -i '0,/blue/{s/blue/39d/}' /home/ubuntu/.oh-my-zsh/themes/agnoster.zsh-theme" ubuntu
  - chsh -s /usr/bin/zsh ubuntu
  - su -c "mkdir /home/ubuntu/.kube" ubuntu
  - cloud-init single --name write_files --frequency once
  - su -c "ssh-keygen -b 2048 -t rsa -q -N '' -f /home/ubuntu/.ssh/id_rsa" ubuntu
  - mkdir /run/tmp
  # versions
  - export KUBECTL_VERSION="v1.19.2"
  - export HELM_VERSION="v3.5.2"
  - export K3SUP_VERSION="0.10.2"
  # install kubectl
  - | 
    cd /run/tmp && curl -LO https://storage.googleapis.com/kubernetes-release/release/$KUBECTL_VERSION/bin/linux/amd64/kubectl \
    && chmod +x ./kubectl \
    && mv ./kubectl /usr/local/bin/kubectl
  # auto-complete for kubectl and alias
  - | 
    echo "source <(kubectl completion zsh)" >> /home/ubuntu/.zshrc
    echo "alias k=kubectl" >> /home/ubuntu/.zshrc
    echo "complete -F __start_kubectl k" >> /home/ubuntu/.zshrc
  # install helm
  - |
    cd /run/tmp && curl -LO https://get.helm.sh/helm-${HELM_VERSION}-linux-amd64.tar.gz \
    && tar -xzvf ./helm-${HELM_VERSION}-linux-amd64.tar.gz \
    && chmod +x ./linux-amd64/helm \
    && mv ./linux-amd64/helm /usr/local/bin/helm
  # install kubectx & kubens
  - |
    git clone https://github.com/ahmetb/kubectx /opt/kubectx
    ln -s /opt/kubectx/kubectx /usr/local/bin/kubectx
    ln -s /opt/kubectx/kubens /usr/local/bin/kubens
    mkdir -p /home/ubuntu/.oh-my-zsh/completions
    chmod -R 755 /home/ubuntu/.oh-my-zsh/completions
    ln -s /opt/kubectx/completion/kubectx.zsh /home/ubuntu/.oh-my-zsh/completions/_kubectx.zsh
    ln -s /opt/kubectx/completion/kubens.zsh /home/ubuntu/.oh-my-zsh/completions/_kubens.zsh
  # install k3sup
  - | 
    cd /run/tmp && curl -LO https://github.com/alexellis/k3sup/releases/download/${K3SUP_VERSION}/k3sup \
    && chmod +x ./k3sup \
    && mv ./k3sup /usr/local/bin/k3sup
